version: "24.0.6"
services:

  # Eureka
  eurekaServer:
    build:
      context: ./EurekaServer
    ports:
      - "8761:8761"
    image: "eureka"

  # Candidat
  CandidatMS:
    build:
      context: ./CandidatMS
    ports:
      - "8888:8081"
    image: "candidatms"
    depends_on:
      - eurekaServer
    environment:
      - eureka.client.service-url.defaultZone=http://eurekaServer:8761/eureka/

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: jobms
      MYSQL_DATABASE: jobMS
      MYSQL_USER: root


  # Job
  JobMS:
    build:
      context: ./JobMS
    ports:
      - "8882:8082"
    image: "jobms"
    depends_on:
      - eurekaServer
      - mysql
    environment:
      - eureka.client.service-url.defaultZone=http://eurekaServer:8761/eureka/
      - spring.datasource.url=jdbc:mysql://mysql:3306/jobMS?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=

  # Gateway
  gateway:
    build:
      context: ./gateway
    ports:
      - "8881:8989"
    image: "gateway"
    depends_on:
      - eurekaServer
    environment:
      - eureka.client.service-url.defaultZone=http://eurekaServer:8761/eureka/

